### ISSUE TITLE
ChipSHOUTER Mounting Bracket files are missing

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/ChipShover#1]
The 3D printed mounting bracket files are missing (in case people want to 3D print them).

**Comment by r0b0tsp1k3** [comment]
Please share these 3D files (STL) soon. The original bracket is hard to clip things onto so I want to "remix" the design: add attachment points to automatically switch to other tools such as chipjabber-basicbbi1 (please share the mounting bracket STL for that too).

**Comment by colinoflynn** [comment]
Should be fixed now - version of it is at https://github.com/newaetech/ChipShover/tree/master/chipshouter_adapter/50mm_mounting_pattern/3dprinted_simple. We had a few variants that will try to upload (also added a newer version that was CNC machined as a reference).

**Comment by colinoflynn** [comment]
Design was done in Fusion360, so have added those source files too (but the history of some of them is very messy, so the Fusion360 files may be less helpful than you hope for).

There was a variant that used the heat set inserts too, I'm checking if I've got the PN for the inserts and will upload that (otherwise it may be easier to modify the hole size to fit the insert you have).
